# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - spraydash

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://ayocontainerazure.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_ae6c4ae3c0414b5496e96d09852a13e9 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_3cc6bea526494ed295f3c7d36794538e }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ayocontainerazure.azurecr.io/spraycash-app:latest
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'spraydash'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_a2c742e39b7849f08cbd4a33dab3001c }}
        images: 'ayocontainerazure.azurecr.io/spraycash-app:latest'